/// Utility class for mapping language codes to readable names
class LanguageMapper {
  static const _languageMap = {
    'en': 'English',
    'eng': 'English',
    'es': 'Spanish',
    'spa': 'Spanish',
    'fr': 'French',
    'fra': 'French',
    'fre': 'French',
    'de': 'German',
    'deu': 'German',
    'ger': 'German',
    'it': 'Italian',
    'ita': 'Italian',
    'pt': 'Portuguese',
    'por': 'Portuguese',
    'ru': 'Russian',
    'rus': 'Russian',
    'ja': 'Japanese',
    'jp': 'Japanese',
    'jpn': 'Japanese',
    'ko': 'Korean',
    'kor': 'Korean',
    'zh': 'Chinese',
    'chi': 'Chinese',
    'zho': 'Chinese',
    'ar': 'Arabic',
    'ara': 'Arabic',
    'hi': 'Hindi',
    'hin': 'Hindi',
    'nl': 'Dutch',
    'nld': 'Dutch',
    'sv': 'Swedish',
    'swe': 'Swedish',
    'no': 'Norwegian',
    'nor': 'Norwegian',
    'da': 'Danish',
    'dan': 'Danish',
    'fi': 'Finnish',
    'fin': 'Finnish',
    'pl': 'Polish',
    'pol': 'Polish',
    'tr': 'Turkish',
    'tur': 'Turkish',
    'he': 'Hebrew',
    'heb': 'Hebrew',
    'th': 'Thai',
    'tha': 'Thai',
    'vi': 'Vietnamese',
    'vie': 'Vietnamese',
    'id': 'Indonesian',
    'ind': 'Indonesian',
    'ms': 'Malay',
    'msa': 'Malay',
    'el': 'Greek',
    'ell': 'Greek',
    'gre': 'Greek',
    'cs': 'Czech',
    'ces': 'Czech',
    'cze': 'Czech',
    'hu': 'Hungarian',
    'hun': 'Hungarian',
    'ro': 'Romanian',
    'ron': 'Romanian',
    'rum': 'Romanian',
    'uk': 'Ukrainian',
    'ukr': 'Ukrainian',
  };

  /// Get readable language name from code
  static String getLanguageName(String code) {
    final lowerCode = code.toLowerCase().trim();
    return _languageMap[lowerCode] ?? code.toUpperCase();
  }
}
