name: PR Checks

on:
  pull_request:
    branches: [main, master, dev, dev-new]

env:
  # Using Flutter 3.27.1 with a patch for media_kit_video compatibility
  FLUTTER_VERSION: "3.27.1"

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze

      - name: Check formatting
        run: dart format --set-exit-if-changed .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  build-check:
    name: Quick Build Check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: flutter-${{ hashFiles('scripts/patch_media_kit.sh') }}

      - name: Install Android SDK & NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-36"
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.12077973"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.0.12077973" >> $GITHUB_ENV

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Clean cached media_kit_video (ensure fresh patch)
        run: rm -rf $HOME/.pub-cache/hosted/*/media_kit_video-* || true

      - name: Re-get media_kit_video
        run: flutter pub get

      - name: Patch media_kit_video for Flutter 3.27
        run: bash scripts/patch_media_kit.sh

      - name: Build APK (debug)
        run: flutter build apk --debug
